version: "3"
services:
  gangway:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-gangway
    command: gangway DEADBEEF-0000-0000-0000-0000CAFEFEED
    depends_on:
      - redis
    ports:
      - 8080:48048
  manager:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-manager
    command: manager DEADBEEF-0000-0000-0000-0000CAFEFEED
    depends_on:
      - redis
  orchestrator:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-orchestrator
    command: orchestrator docker -p 5 --storage s3+http://minioadmin:minioadmin@webgrid-s3:9000/webgrid-video?pathStyle DEADBEEF-0000-0000-0000-0000CAFEFEED "${REPOSITORY:-webgrid}/node-firefox:${IMAGE_TAG:-latest}=firefox::68.7.0esr,${REPOSITORY:-webgrid}/node-chrome:${IMAGE_TAG:-latest}=chrome::81.0.4044.122"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  redis:
    image: redis:6.2-alpine
    container_name: webgrid-redis
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
  s3:
    image: minio/minio
    container_name: webgrid-s3
    entrypoint: sh
    command: -c 'mkdir -p /export/webgrid-video && /usr/bin/minio server /export --console-address ":44095"'
    ports:
      - 44095:44095
      - 9000:9000

networks:
  default:
    external: true
    name: webgrid
