version: "3"
services:
  gangway:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-gangway
    command: gangway DEADBEEF-0000-0000-0000-0000CAFEFEED
    depends_on:
      - redis
    ports:
      - 8080:48048
  manager:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-manager
    command: manager DEADBEEF-0000-0000-0000-0000CAFEFEED
    depends_on:
      - redis
  orchestrator:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-orchestrator
    command: orchestrator docker -p 5 --storage s3+http://minioadmin:minioadmin@webgrid-s3:9000/webgrid-video?pathStyle DEADBEEF-0000-0000-0000-0000CAFEFEED "${REPOSITORY:-webgrid}/node-firefox:${IMAGE_TAG:-latest}=firefox::68.7.0esr,${REPOSITORY:-webgrid}/node-chrome:${IMAGE_TAG:-latest}=chrome::81.0.4044.122"
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  collector:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-collector
    command: collector DEADBEEF-0000-0000-0000-0000CAFEFEED --mongodb mongodb://root:example@webgrid-mongo:27017/
  api:
    image: ${REPOSITORY:-webgrid}/core:${IMAGE_TAG:-latest}
    platform: linux/amd64
    container_name: webgrid-api
    command: api --mongodb mongodb://root:example@webgrid-mongo:27017/ --host webgrid-api
  redis:
    image: redis:6.2-alpine
    container_name: webgrid-redis
    command: redis-server --save "" --appendonly no
    ports:
      - 6379:6379
  s3:
    image: minio/minio@sha256:9daf9c4b2be5b19b8bf40d3cc9a6026b94d9b31582deb7365914b27c09e28573
    container_name: webgrid-s3
    entrypoint: sh
    command: -c 'mkdir -p /storage/webgrid-video && /usr/bin/docker-entrypoint.sh server /storage --console-address ":44095"'
    ports:
      - 44095:44095
      - 9000:9000
  mongo:
    image: mongo
    container_name: webgrid-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  mongo-express:
    image: mongo-express
    container_name: webgrid-mongoexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@webgrid-mongo:27017/

networks:
  default:
    external: true
    name: webgrid
