[package]
name = "library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Everyday stuff
tokio = "1.6"
async-trait = "0.1"
lazy_static = "1.4"
thiserror = "1.0"
anyhow = "1.0"
futures = "0.3"

# Proxying
hyper = { version = "0.14", features = ["full"] }
paste = "1.0"

# Data serialization
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"

# Tracing, Metrics & Co.
tracing = { git = "https://github.com/tokio-rs/tracing", version = "0.2", features = ["log"] }

# Data handling & caching
rust-s3 = { version = "0.27.0-rc4", git = "https://github.com/durch/rust-s3" }
redis = { version = "0.20.2-alpha.0", default-features = false, features = ["tokio-comp", "streams"], git = "https://github.com/TilBlechschmidt/redis-rs", branch = "webgrid-state" }
mongodb = { version = "2.0", features = ["bson-uuid-0_8", "bson-chrono-0_4"] }
rand = "0.8"
lru = "0.6"

# Test dependencies
pretty_assertions = { version = "0.7", optional = true }

[dev-dependencies]
reqwest = "0.11"
uuid = { version = "0.8", features = ["v4", "serde"] }

[features]
test = ["pretty_assertions"]
