apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-manager
  labels:
    web-grid/component: manager
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.manager }}
  selector:
    matchLabels:
      web-grid/component: manager
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: manager
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.manager }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.manager }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.manager }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}/core:{{ include "web-grid.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-manager
          args: ["manager", "--status-server"]
          ports:
            - name: http
              containerPort: 40001
              protocol: TCP
            - name: status
              containerPort: 47002
              protocol: TCP
          env:
            - name: REDIS
              value: "{{ include "web-grid.redisURL" . }}"
            - name: MANAGER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
          livenessProbe:
            tcpSocket:
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          resources:
            {{- toYaml .Values.resources.manager | nindent 12 }}