apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-orchestrator
  labels:
    web-grid/component: orchestrator
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.orchestrator }}
  selector:
    matchLabels:
      web-grid/component: orchestrator
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: orchestrator
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "web-grid.serviceAccountName" . }}
      {{- with .Values.nodeSelector.orchestrator }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.orchestrator }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.orchestrator }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: orchestrator-config
          configMap:
            name: {{ include "web-grid.fullname" . }}-orchestrator
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}/core:{{ include "web-grid.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-orchestrator
          args: ["orchestrator", "kubernetes", "--status-server"]
          volumeMounts:
            - name: orchestrator-config
              mountPath: /configs
          ports:
            - name: status
              containerPort: 47002
              protocol: TCP
          env:
            - name: REDIS
              value: "{{ include "web-grid.redisURL" . }}"
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SLOT_COUNT
              value: "{{ .Values.maxSessionsPerOrchestrator }}"
            - name: IMAGES
              value: "{{ .Values.image.repository }}/node-firefox:{{ include "web-grid.imageTag" . }}=firefox::68.7.0esr,{{ .Values.image.repository }}/node-chrome:{{ include "web-grid.imageTag" . }}=chrome::81.0.4044.122"
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: WEBGRID_CONFIG_DIR
              value: "/configs"
            - name: WEBGRID_RESOURCE_PREFIX
              value: "{{ include "web-grid.fullname" . }}-"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            tcpSocket:
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          resources:
            {{- toYaml .Values.resources.orchestrator | nindent 12 }}
