apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-proxy
  labels:
    web-grid/component: proxy
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.proxy }}
  selector:
    matchLabels:
      web-grid/component: proxy
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: proxy
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.proxy }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.proxy }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.proxy }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}/core:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-proxy
          args: ["proxy", "--status-server"]
          ports:
            - name: http
              containerPort: 40005
              protocol: TCP
            - name: status
              containerPort: 47002
              protocol: TCP
          env:
            - name: REDIS
              value: "{{ include "web-grid.redisURL" . }}"
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
          livenessProbe:
            tcpSocket:
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          resources:
            {{- toYaml .Values.resources.proxy | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-grid.fullname" . }}
  labels:
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    web-grid/component: proxy
    {{- include "web-grid.selectorLabels" . | nindent 4 }}
