{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "web-grid.serviceAccountName" . }}
  labels:
    {{- include "web-grid.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "web-grid.serviceAccountName" . }}
rules:
  - apiGroups: ["batch", ""] # "" indicates the core API group
    resources: ["jobs", "pods"]
    verbs: ["delete", "create", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "web-grid.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "web-grid.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "web-grid.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}