{{- if .Values.recording.enabled }}
{{- if .Values.recording.createVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web-grid.recordingPVCName" . }}
  labels:
    web-grid/component: storage
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.recording.persistentVolumeClaim.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.recording.sizeLimit }}
---
{{- end}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "web-grid.fullname" . }}-storage
  labels:
    web-grid/component: storage
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      web-grid/component: storage
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: storage
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.storage }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.storage }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.storage }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "web-grid.recordingPVCName" . }}
      containers:
        - image: "{{ .Values.image.repository }}/webgrid"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-storage
          args: ["storage", "--status-server"]
          volumeMounts:
            - name: storage
              mountPath: /storage
          ports:
            - name: http
              containerPort: 40006
              protocol: TCP
            - name: status
              containerPort: 47002
              protocol: TCP
          env:
            - name: REDIS
              value: "{{ include "web-grid.redisURL" . }}"
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: STORAGE_DIRECTORY
              value: "/storage"
          livenessProbe:
            tcpSocket:
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          resources:
            {{- toYaml .Values.resources.storage | nindent 12 }}
{{- end }}