{{- if .Values.telemetry.demo }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-grid.fullname" . }}-telemetry
  labels:
      {{- include "web-grid.labels" . | nindent 6 }}
data:
  otel.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:

    exporters:
      logging:
          loglevel: debug

      jaeger:
          endpoint: localhost:14250
          insecure: true

    processors:
      batch:

    extensions:
      health_check:

    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging, jaeger]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-telemetry
  labels:
    web-grid/component: telemetry
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      web-grid/component: telemetry
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: telemetry
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.telemetryDemo }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.telemetryDemo }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.telemetryDemo }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: otel-config
          configMap:
            name: {{ include "web-grid.fullname" . }}-telemetry
      containers:
        - image: otel/opentelemetry-collector-dev:latest
          imagePullPolicy: IfNotPresent
          name: {{ .Chart.Name }}-otelcol
          args: ['--config=/config/otel.yaml']
          ports:
            - name: grpc
              containerPort: 4317
              protocol: TCP
            - name: status
              containerPort: 13133
              protocol: TCP
          volumeMounts:
            - name: otel-config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: status
          resources:
            {{- toYaml .Values.resources.telemetryDemo | nindent 12 }}
        - image: jaegertracing/all-in-one:latest
          name: {{ .Chart.Name }}-jaeger
          imagePullPolicy: IfNotPresent
          ports:
            - name: jaeger-ui
              containerPort: 16686
              protocol: TCP
            - name: data-ingress
              containerPort: 14250
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.telemetryDemo | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-grid.fullname" . }}-telemetry
  labels:
    web-grid/component: telemetry
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  ports:
    - port: 4317
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 16686
      targetPort: jaeger-ui
      protocol: TCP
      name: jaeger-ui
  selector:
    web-grid/component: telemetry
    {{- include "web-grid.selectorLabels" . | nindent 4 }}
{{- end}}
