# Project information
site_name: WebGrid
site_description: Decentralized, scalable and robust implementation of a selenium-grid equivalent. Based on the WebDriver specification by the W3C.
site_author: Til Blechschmidt
site_url: https://webgrid.dev/

# Repository
repo_name: TilBlechschmidt/WebGrid
repo_url: https://github.com/TilBlechschmidt/WebGrid
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2019 - 2020 Til Blechschmidt

# Navigation
nav:
  - "Home":
      - "index.md"
      - "getting-started.md"
      - "faq.md"
  - "Features":
      - "features/api.md"
      - "features/screen-recording.md"
      - "features/hybrid-grid.md"
  - "Kubernetes":
      - "kubernetes/configuration.md"
      - "kubernetes/access.md"
      - "kubernetes/storage.md"
      - "kubernetes/scaling.md"
  - "Guides":
      - "guides/k3s.md"
  - "|":
      - "--separator--"
  - "Contribute":
      - "contribute/index.md"
      - "contribute/issues.md"
      - "contribute/code-contrib.md"
      - "contribute/dev-environment.md"
      - "contribute/release.md"
      - "Code of conduct": "contribute/code-of-conduct.md"
  - "Architecture":
      - "architecture/index.md"
      - "architecture/database.md"
      - "architecture/structure.md"
      - "architecture/services.md"
      - "architecture/error-handling.md"
      - "architecture/workflows.md"
      - "architecture/discovery.md"
  - "Issue Tracker":
      - "https://github.com/TilBlechschmidt/WebGrid/issues"

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: teal
    accent: teal
    scheme: preference
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs

extra_css:
  - docs.css

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TilBlechschmidt
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/themegatb
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/webgrid
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yYaPcNM

# Plugins
plugins:
  - search
  - git-revision-date-localized
  - codeinclude
  - mermaid2:
      arguments:
        theme: "dark"
  - helm-repo:
      chart: distribution/kubernetes/chart
      helm_repo_url: https://webgrid.dev/
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:on_post_build"

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

# Extensions
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
