apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: manager
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      name: manager
  template:
    metadata:
      labels:
        name: manager
    spec:
      containers:
        - image: registry.blechschmidt.de/webgrid-manager
          imagePullPolicy: Always
          name: manager
          ports:
            - containerPort: 40001
          env:
            - name: WEBGRID_REDIS_URL
              value: "redis://redis/"
            - name: WEBGRID_MANAGER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WEBGRID_MANAGER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RUST_LOG
              value: info
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /status
              port: 40001
      initContainers:
        - name: init-redis
          image: redis:alpine
          command: ['sh', '-c', "until redis-cli -h redis PING; do echo waiting for redis; sleep 2; done"]
