apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: metrics
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metrics
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3036"
      labels:
        name: metrics
    spec:
      containers:
        - image: registry.blechschmidt.de/webgrid-metrics
          imagePullPolicy: Always
          name: metrics
          ports:
            - containerPort: 3036
          env:
            - name: WEBGRID_REDIS_URL
              value: "redis://redis/"
            - name: RUST_LOG
              value: info,warp=debug
      initContainers:
        - name: init-redis
          image: redis:alpine
          command: ['sh', '-c', "until redis-cli -h redis PING; do echo waiting for redis; sleep 2; done"]
