apiVersion: v1
kind: ServiceAccount
metadata:
  name: webgrid-robot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webgrid-job-creator
rules:
  - apiGroups: ["batch", ""] # "" indicates the core API group
    resources: ["jobs", "services"]
    verbs: ["delete", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: webgrid-job-creator
subjects:
  - kind: ServiceAccount
    name: webgrid-robot
roleRef:
  kind: Role
  name: webgrid-job-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orchestrator
  template:
    metadata:
      labels:
        name: orchestrator
    spec:
      serviceAccountName: webgrid-robot
      containers:
        - image: registry.blechschmidt.de/webgrid-orchestrator:k8s
          imagePullPolicy: Always
          name: orchestrator
          env:
            - name: WEBGRID_REDIS_URL
              value: "redis://redis/"
            - name: WEBGRID_ORCHESTRATOR_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WEBGRID_SLOTS
              value: "5"
            - name: WEBGRID_IMAGES
              value: registry.blechschmidt.de/webgrid-node:firefox=firefox::68.7.0esr,registry.blechschmidt.de/webgrid-node:chrome=chrome::81.0.4044.122
            - name: RUST_LOG
              value: info
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      initContainers:
        - name: init-redis
          image: redis:alpine
          command: ['sh', '-c', "until redis-cli -h redis PING; do echo waiting for redis; sleep 2; done"]
