apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: proxy
  template:
    metadata:
      labels:
        name: proxy
    spec:
      containers:
        - image: registry.blechschmidt.de/webgrid-proxy
          imagePullPolicy: Always
          name: proxy
          ports:
            - containerPort: 40005
          env:
          - name: WEBGRID_REDIS_URL
            value: "redis://redis/"
          - name: RUST_LOG
            value: debug,hyper=warn
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /status
              port: 40005
      initContainers:
        - name: init-redis
          image: redis:alpine
          command: ['sh', '-c', "until redis-cli -h redis PING; do echo waiting for redis; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  ports:
    - port: 80
      targetPort: 40005
      protocol: TCP
  selector:
    name: proxy
