[workspace]
members = [
	"binary",
	"libraries/helpers",
	"libraries/resources",
	"libraries/lifecycle",
	"libraries/scheduling",
	"libraries/storage",
	"libraries/testing",
]

[profile.release]
lto = true
