[workspace]
members = [
	"webgrid",
	"libraries/helpers",
	"libraries/resources",
	"libraries/lifecycle",
	"libraries/scheduling",
	"libraries/testing",
	"manager",
	"node",
	"proxy",
	"orchestrators/core",
	"orchestrators/docker",
	"orchestrators/k8s",
	"metrics"
]

[profile.release]
lto = true