apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-grid.fullname" . }}-redis
  labels:
      web-grid/component: orchestrator
      {{- include "web-grid.labels" . | nindent 6 }}
data:
  # ------- TODO Replace maxmemory with calculated value! -------
  redis.conf: |
    notify-keyspace-events "Kgx"
    maxmemory 100mb

    # RDB Snapshots
    save 900 1
    save 300 10
    save 60 10000
    
    dbfilename dump.rdb
    dir /data

    # AOF Persistence
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-grid.fullname" . }}-orchestrator
  labels:
      web-grid/component: orchestrator
      {{- include "web-grid.labels" . | nindent 6 }}
data:
  job.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: {{ "{{job_name}}" }}
      labels:
        web-grid/component: node
        web-grid/sessionID: {{ "{{session_id}}" }}
        {{- include "web-grid.labels" . | nindent 8 }}
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            web-grid/component: node
            web-grid/sessionID: {{ "{{session_id}}" }}
            {{- include "web-grid.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.nodeSelector.session }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity.session }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations.session }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: Never
          volumes:
            - name: dshm
              emptyDir:
                medium: Memory
          containers:
            - name: {{ "{{job_name}}" }}
              image: {{ "{{image_name}}" }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
                - name: http
                  containerPort: 40003
                  protocol: TCP
              env:
                - name: RUST_LOG
                  value: {{ .Values.logLevel }}
                - name: ID
                  value: {{ "{{session_id}}" }}
                - name: REDIS
                  value: "{{ include "web-grid.redisURL" . }}"
              volumeMounts:
                - mountPath: /dev/shm
                  name: dshm
              resources:
                {{- toYaml .Values.resources.session | nindent 16 }}
  service.yaml: |
    apiVersion: v1
    kind: Service
    metadata:
      name: {{ "{{service_name}}" }}
      ownerReferences:
        - apiVersion: v1
          controller: true
          blockOwnerDeletion: false
          kind: Job
          name: {{ "{{job_name}}" }}
          uid: {{ "{{job_uid}}" }}
    spec:
      ports:
        - port: 40003
          targetPort: http
          protocol: TCP
      selector:
        web-grid/component: node
        web-grid/sessionID: {{ "{{session_id}}" }}
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
