apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-orchestrator
  labels:
    web-grid/component: orchestrator
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.orchestrator }}
  selector:
    matchLabels:
      web-grid/component: orchestrator
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: orchestrator
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "web-grid.serviceAccountName" . }}
      {{- with .Values.nodeSelector.orchestrator }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.orchestrator }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.orchestrator }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: orchestrator-config
          configMap:
            name: {{ include "web-grid.fullname" . }}-orchestrator
      containers:
        - image: "{{ .Values.image.repository }}/webgrid-orchestrator:k8s"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-orchestrator
          volumeMounts:
            - name: orchestrator-config
              mountPath: /configs
          ports:
            - name: health-probe
              containerPort: 40004
              protocol: TCP
          env:
            - name: WEBGRID_REDIS_URL
              value: "{{ include "web-grid.redisURL" . }}"
            - name: WEBGRID_ORCHESTRATOR_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WEBGRID_SLOTS
              value: "5"
            - name: WEBGRID_IMAGES
              value: "{{ .Values.image.repository }}/webgrid-node:firefox=firefox::68.7.0esr,{{ .Values.image.repository }}/webgrid-node:chrome=chrome::81.0.4044.122"
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: WEBGRID_CONFIG_DIR
              value: "/configs"
            - name: WEBGRID_RESOURCE_PREFIX
              value: "{{ include "web-grid.fullname" . }}-"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /status
              port: health-probe
          readinessProbe:
            httpGet:
              path: /status
              port: health-probe
          resources:
            {{- toYaml .Values.resources.orchestrator | nindent 12 }}
      initContainers:
        - name: init-redis
          image: redis:alpine
          command: ['sh', '-c', "until redis-cli -h {{ include "web-grid.redisServiceName" . }} PING; do echo waiting for redis; sleep 2; done"]
