apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-proxy
  labels:
    web-grid/component: proxy
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.proxy }}
  selector:
    matchLabels:
      web-grid/component: proxy
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        web-grid/component: proxy
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.proxy }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.proxy }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.proxy }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - image: "{{ .Values.image.repository }}/webgrid-proxy"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-proxy
          ports:
            - name: http
              containerPort: 40005
              protocol: TCP
          env:
          - name: WEBGRID_REDIS_URL
            value: "{{ include "web-grid.redisURL" . }}"
          - name: RUST_LOG
            value: {{ .Values.logLevel }}
          livenessProbe:
            httpGet:
              path: /status
              port: http
          readinessProbe:
            httpGet:
              path: /status
              port: http
          resources:
            {{- toYaml .Values.resources.proxy | nindent 12 }}
      initContainers:
        - name: init-redis
          image: redis:alpine
          command: ['sh', '-c', "until redis-cli -h {{ include "web-grid.redisServiceName" . }} PING; do echo waiting for redis; sleep 2; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-grid.fullname" . }}
  labels:
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    web-grid/component: proxy
    {{- include "web-grid.selectorLabels" . | nindent 4 }}
