//! Constant values
//!
//! This module contains constants generated by the build script. The values in this module are sourced from the constants.yml file.

include!(concat!(env!("OUT_DIR"), "/constants.rs"));
