apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "web-grid.fullname" . }}-gangway
  labels:
    dev.webgrid/component: gangway
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "web-grid.fullname" . }}-gangway
  replicas: {{ .Values.replicaCount.gangway }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      dev.webgrid/component: gangway
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        dev.webgrid/component: gangway
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.gangway }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.gangway }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.gangway }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      {{- end }}
      terminationGracePeriodSeconds: {{ add .Values.config.gangway.terminationGracePeriod 20 }}
      containers:
        - image: "{{ .Values.image.repository }}/core:{{ include "web-grid.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}-gangway
          args: ["gangway", "--status-server", "47002"]
          ports:
            - name: http
              containerPort: 48048
              protocol: TCP
            - name: status
              containerPort: 47002
              protocol: TCP
          env:
            - name: REDIS
              value: "{{ include "web-grid.redisURL" . }}"
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
            - name: CACHE_SIZE
              value: "{{ .Values.config.gangway.cacheSize }}"
            - name: PENDING_REQUEST_LIMIT
              value: "{{ .Values.config.gangway.pendingRequestLimit }}"
            - name: TERMINATION_GRACE_PERIOD
              value: "{{ .Values.config.gangway.terminationGracePeriod }}"
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- if .Values.config.storageBackend }}
            - name: STORAGE
              valueFrom:
                secretKeyRef:
                  name: {{ include "web-grid.fullname" . }}-storage
                  key: url
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: status
          readinessProbe:
            periodSeconds: 3
            failureThreshold: 1
            httpGet:
              path: /status
              port: status
          resources:
            {{- toYaml .Values.resources.gangway | nindent 12 }}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "web-grid.fullname" . }}-gangway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      dev.webgrid/component: gangway
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
