{{- if not .Values.config.redis.customEndpoint -}}
{{- if ne .Values.config.redis.storageClassName "emptyDir" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "web-grid.fullname" . }}-redis
  labels:
    dev.webgrid/component: redis
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.config.redis.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-grid.fullname" . }}-redis
  labels:
      dev.webgrid/component: redis
      {{- include "web-grid.labels" . | nindent 6 }}
data:
  # ------- TODO Replace maxmemory with calculated value! -------
  redis.conf: |
    maxmemory 100mb

    # RDB Snapshots
    save 900 1
    save 300 10
    save 60 10000
    
    dbfilename dump.rdb
    dir /data

    # AOF Persistence
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble yes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-grid.fullname" . }}-redis
  labels:
    dev.webgrid/component: redis
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      dev.webgrid/component: redis
      {{- include "web-grid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
      labels:
        dev.webgrid/component: redis
        {{- include "web-grid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector.redis }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity.redis }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations.redis }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: redis-config
          configMap:
            name: {{ include "web-grid.fullname" . }}-redis
        - name: redis-persistence
          {{- if eq .Values.config.redis.storageClassName "emptyDir" }}
          emptyDir:
            medium: Memory
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "web-grid.fullname" . }}-redis
          {{- end }}
      containers:
        - image: redis:6.2-alpine
          imagePullPolicy: IfNotPresent
          name: {{ .Chart.Name }}-redis
          args: ['/config/redis.conf']
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          volumeMounts:
            - name: redis-config
              mountPath: /config
            - name: redis-persistence
              mountPath: /data
          resources:
            {{- toYaml .Values.resources.redis | nindent 12 }}
        - image: oliver006/redis_exporter:latest
          name: redis-exporter
          ports:
            - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-grid.redisServiceName" . }}
  labels:
    {{- include "web-grid.labels" . | nindent 4 }}
spec:
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    dev.webgrid/component: redis
    {{- include "web-grid.selectorLabels" . | nindent 4 }}
{{- end }}