apiVersion: v1
kind: Service
metadata:
  name: {{service_name}}
  ownerReferences:
    - apiVersion: v1
      controller: true
      blockOwnerDeletion: true
      kind: Job
      name: {{job_name}}
      uid: {{job_uid}}
spec:
  ports:
    - port: 40003
      targetPort: 40003
      protocol: TCP
  selector:
    app: {{job_name}}
