apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "webgrid-demo.fullname" . }}-storage
spec:
  storageClassName: {{ .Values.volumeClaim.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volumeClaim.request }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webgrid-demo.fullname" . }}-storage
  labels:
    dev.webgrid/component: minio
    {{- include "webgrid-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      dev.webgrid/component: minio
      {{- include "webgrid-demo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        dev.webgrid/component: minio
        {{- include "webgrid-demo.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "webgrid-demo.fullname" . }}-storage
      terminationGracePeriodSeconds: 10
      containers:
        - name: minio
          image: minio/minio:latest
          volumeMounts:
            - mountPath: "/storage"
              name: storage
          command:
            [
              "/bin/bash",
              "-c",
              'mkdir -p /storage/webgrid-video && /usr/bin/minio server /storage --console-address ":44095"',
            ]
          ports:
            - name: s3
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 44095
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
  # Unfortunately, due to the way helm works, we may not use any templating in here.
  # In the values.yaml, we override the webgrid storageBackend to use this name and
  # as the values.yaml does not allow templating, there is no way to parametrize this with e.g. the release name.
  name: webgrid-demo-storage
  labels:
    {{- include "webgrid-demo.labels" . | nindent 4 }}
spec:
  ports:
    - name: s3
      protocol: TCP
      port: 80
      targetPort: 9000
    - name: console
      protocol: TCP
      port: 8080
      targetPort: 44095
  selector:
    dev.webgrid/component: minio
    {{- include "webgrid-demo.selectorLabels" . | nindent 4 }}
