name: ⌛️ Mark stale issues and pull requests

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue had no recent activity. It will be auto-closed in five days if no further actions are taken."
          stale-pr-message: "This PR had no recent activity. It will be auto-closed in five days if no further actions are taken."
          stale-issue-label: "Status: Abandoned"
          exempt-issue-labels: "Status: Accepted,Status: Available,Status: Blocked"
          stale-pr-label: "Status: Abandoned"
          exempt-pr-labels: "Status: Review Needed,Status: In Progress"
